server:
  maxThreads: 128
  minThreads: 128
  applicationConnectors:
    - type: http
      port: 8090
  adminConnectors:
    - type: http
      port: 8091
  applicationContextPath: /
  requestLog:
    appenders:
      - type: console
        timeZone: IST

logging:
  level: INFO
  loggers:
    com.phonepe: INFO
    org.hibernate: ERROR
  appenders:
    - type: console
      threshold: INFO
      timeZone: IST
      logFormat: "%(%-5level) [%date] [%thread] [%logger{0}]: %message%n"


shardConfig:
  shards:
    - driverClass: org.mariadb.jdbc.Driver
      user: "root"
      password: "admin123"
      url: jdbc:mariadb://localhost/todolist_db1?createDatabaseIfNotExist=true
      properties:
        charSet: UTF-8
        hibernate.dialect: org.hibernate.dialect.MariaDBDialect
        hibernate.hbm2ddl.auto: update
        hibernate.show_sql: true
      maxWaitForConnection: 1s
      validationQuery: "/* MyApplication Health Check */ SELECT 1"
      minSize: 8
      maxSize: 8
      initialSize: 8
      checkConnectionWhileIdle: false

    - driverClass: org.mariadb.jdbc.Driver
      user: "root"
      password: "admin123"
      url: jdbc:mariadb://localhost/todolist_db2?createDatabaseIfNotExist=true
      properties:
        charSet: UTF-8
        hibernate.dialect: org.hibernate.dialect.MariaDBDialect
        hibernate.hbm2ddl.auto: update
        hibernate.show_sql: true
      maxWaitForConnection: 1s
      validationQuery: "/* MyApplication Health Check */ SELECT 1"
      minSize: 8
      maxSize: 8
      initialSize: 8
      checkConnectionWhileIdle: false